const badAffirmations = [
  "You’re not lazy. You’re just on energy-saving mode.",
  "Today is the day to give up on tomorrow.",
  "You’re one step closer to your next mistake.",
  "Remember, it’s not procrastination if you never planned to do it.",
  "Success is overrated. Mediocrity feels just fine.",
  "Mistakes are proof that you’re trying... badly.",
  "Why try your best when 'meh' will do?",
  "Self-care means ignoring all responsibilities, right?",
  "You don’t have to outrun your problems, just hide better.",
  "Everyone else is faking it too.",
  "Don’t worry, you’re someone else’s problem.",
  "Your potential is limitless, but so is your ability to waste it.",
  "Perfection is unattainable. Good thing you're far from it.",
  "Dream big, then hit snooze and forget about it.",
  "Life’s short. Skip the hard stuff.",
  "If at first you don’t succeed, redefine success.",
  "Your future self will regret this, but that’s not your problem.",
  "Why aim for the stars when the couch is so comfy?",
  "You’ve got this! Or maybe you don’t. Who knows?",
  "Don't be afraid to fail... unless people are watching.",
  "You can’t please everyone. So stop trying entirely.",
  "Your mistakes will be legendary… for all the wrong reasons.",
  "The glass isn’t half full or empty. It’s just dirty.",
  "Life’s a rollercoaster, but you're stuck in the gift shop.",
  "You’re special… like the caution tape at a crime scene.",
  "Confidence is key, but you seem to have misplaced it.",
  "The best way to predict the future is to avoid planning it.",
  "Nobody else knows what they're doing either. Join the club.",
  "You’re doing great… at setting the bar really low.",
  "Failure is always an option, and you're great at finding it.",
  "Your comfort zone has free snacks. Stay there.",
  "Be yourself, unless you can be someone better.",
  "Hustle hard? Nah, nap harder.",
  "Follow your dreams... unless they're too much effort.",
  "You miss 100% of the naps you don’t take.",
  "It’s okay to quit. Winners never start in the first place.",
  "Your vibe attracts your tribe, so good luck with that.",
  "Believe in yourself. No one else does, but that’s fine.",
  "You’re exactly where you’re supposed to be: confused.",
  "You don’t need to shine. Dim lights are cozy too.",
  "Aim low and you’ll never be disappointed.",
  "Keep doing what you’re doing. It’s not working, but oh well.",
  "You're not behind; you're just on your own weird timeline.",
  "You can't lose if you don't try.",
  "Take the road less traveled... because you’re lost.",
  "Your best is good enough. For now, just exist.",
  "Embrace your flaws. There’s a lot to love (or tolerate).",
  "Every cloud has a silver lining… unless it rains on you.",
  "You’re the best version of yourself... at avoiding effort.",
  "Life’s a marathon, but you’re walking the wrong way.",
  "Remember, there’s no 'I' in quit… wait.",
  "Failure is a stepping stone to mediocrity.",
  "Keep your expectations low, and life won’t disappoint you.",
  "You’re a diamond in the rough… mostly rough.",
  "You are unique… just like everyone else.",
  "Shoot for the moon. At least you’ll land in debt.",
  "It's not about the journey or the destination. It's about snacks.",
  "Your comfort zone called. It says, 'Stay forever.'",
  "Do less. It’s working for you so far.",
  "Sometimes doing nothing is the best you can do. Congrats!",
  "Life’s too short to care too much.",
  "You are the protagonist of your own bad decisions.",
  "Why fit in when you can stand out awkwardly?",
  "You’re the hero of your story, but the villain is winning.",
  "No one can stop you… except yourself.",
  "You’re proof that even chaos can survive.",
  "Your inner child is crying. Just ignore them.",
  "Remember, you're someone's reason to smile… sarcastically.",
  "The world is your oyster… but you’re allergic.",
  "Everything happens for a reason, and that reason is you.",
  "You’re an inspiration… for what not to do.",
  "Your potential is infinite. Too bad your motivation isn’t.",
  "Success is just failure that didn’t stop soon enough.",
  "You’re a work in progress… mostly stalled progress.",
  "Believe in yourself… or don’t. It won’t change much.",
  "You're the missing puzzle piece… of a completely different puzzle.",
  "Why climb the mountain when the view is on Instagram?",
  "Do what you love, even if no one else loves it.",
  "You’re doing the best you can… probably.",
  "The grass is always greener… because it’s artificial.",
  "The early bird gets the worm, but worms are gross.",
  "Life’s a journey, but you forgot the map.",
  "You’re living proof that bad decisions can be fun.",
  "You don’t need a plan. Chaos works just fine.",
  "Your comfort zone isn’t so bad. Stay there.",
  "You’re not failing; you’re redefining success downward.",
  "You’re a trendsetter… in questionable choices.",
  "Remember, it’s not about winning. It’s about survival.",
  "Be yourself… but maybe less awkward.",
  "It’s okay to not have a clue. Join the club.",
  "You are the chaos you want to see in the world.",
  "You’re a masterpiece… in abstract.",
  "Be proud. You’ve made it this far without a manual.",
  "Why worry about tomorrow when today is already a mess?",
  "You’re a trailblazer… but the trail leads nowhere.",
  "Keep your head up… or don’t. Gravity wins anyway.",
  "You’re unstoppable… mostly because you never started.",
  "Be the best you that you can be… or just exist.",
  "Dream big, but don’t wake up.",
  "The best things in life are free… like disappointment.",
  "Remember, you’re the author of your own chaos.",
  "You’re shining… like a dim flashlight.",
  "You’re perfectly flawed. Heavy on the flawed.",
  "You’re growing… like a weed in a cracked sidewalk.",
  "You’re not lost. You’re just exploring poorly.",
  "Taking the same route to work is a great way to make new friends, and stalkers.",
  "You are using incognito but will just download any random app, huh?",
];

export default badAffirmations;
