const goodAffirmations = [
  "You are capable of amazing things.",
  "Every day is a new opportunity to grow and improve.",
  "You have the power to create the life you desire.",
  "Believe in yourself, and you will be unstoppable.",
  "Your potential is limitless, and you are worthy of success.",
  "You are strong, resilient, and can overcome any challenge.",
  "Happiness is a choice, and today you choose joy.",
  "You are enough, just as you are.",
  "You have the courage to face anything life brings your way.",
  "Every step you take is progress, no matter how small.",
  "You are deserving of love, respect, and kindness.",
  "Your mind is powerful, and you can achieve great things.",
  "You are surrounded by love and positivity.",
  "Your hard work is paying off, even if you can’t see it yet.",
  "You have the strength to conquer your fears and doubts.",
  "You are in control of your own happiness.",
  "Your dreams are valid, and you are capable of achieving them.",
  "You are worthy of all the good things in life.",
  "Your kindness and compassion make the world a better place.",
  "You are learning and growing every single day.",
  "You are exactly where you need to be at this moment.",
  "Your positivity is contagious, and you inspire those around you.",
  "You are grateful for all the blessings in your life.",
  "You have the power to turn your thoughts into reality.",
  "You are creating a life filled with love, happiness, and purpose.",
  "You are proud of how far you’ve come and excited for what’s next.",
  "You are calm, centered, and at peace with yourself.",
  "You attract positivity and abundance into your life.",
  "You are a source of light and positivity for others.",
  "You deserve to take time for yourself and prioritize self-care.",
  "You are open to new possibilities and opportunities.",
  "You are confident in your ability to make good decisions.",
  "You are letting go of what no longer serves you and embracing the new.",
  "You are grateful for the journey, not just the destination.",
  "You are capable of achieving greatness, one step at a time.",
  "You are surrounded by people who support and uplift you.",
  "You are worthy of your dreams and aspirations.",
  "You trust yourself to navigate life’s challenges with grace and strength.",
  "You are proud of the person you are becoming.",
  "You are patient with yourself as you grow and heal.",
  "You choose to focus on what you can control and let go of the rest.",
  "You are worthy of love, success, and happiness.",
  "You celebrate your small wins and appreciate your progress.",
  "You are open to learning and growing from every experience.",
  "You radiate confidence, positivity, and peace.",
  "You are deserving of rest and relaxation when you need it.",
  "You are capable of handling whatever comes your way today.",
  "You are grateful for all the love and kindness in your life.",
  "You are constantly evolving into a better version of yourself.",
  "You are stronger than any obstacle in your path.",
  "You trust the timing of your life and embrace the present moment.",
  "You are worthy of achieving your goals and living your dreams.",
  "You are resilient and have the power to bounce back from any setback.",
  "You are at peace with who you are and excited for who you are becoming.",
  "You are enough, and you always have been.",
  "You are capable of finding joy in even the smallest moments.",
  "You are the creator of your own happiness and success.",
  "You are confident in your unique abilities and strengths.",
  "You are grateful for the lessons life has taught you.",
  "You are strong, courageous, and full of potential.",
  "You are proud of your progress and excited for the future.",
  "You have everything you need within you to succeed.",
  "You choose to see the good in yourself and others.",
  "You are in control of your thoughts, and they are positive and uplifting.",
  "You are worthy of living a life that makes you truly happy.",
  "You are proud of the journey you’re on and the person you’re becoming.",
  "You are capable of achieving anything you set your mind to.",
  "You are grateful for the beauty and abundance in your life.",
  "You are kind to yourself and treat yourself with compassion.",
  "You attract positivity, love, and success into your life.",
  "You are focused, driven, and determined to reach your goals.",
  "You are letting go of negativity and embracing the good around you.",
  "You are capable of handling today with strength and confidence.",
  "You are worthy of all the great things life has to offer.",
  "You are a unique and valuable person with so much to offer.",
  "You are learning, growing, and evolving every single day.",
  "You choose to love and accept yourself unconditionally.",
  "You are worthy of love, respect, and endless possibilities.",
  "You have the power to make today a great day.",
];

export default goodAffirmations;
